# Generated by Django 3.1.7 on 2021-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
