# Generated by Django 3.1.7 on 2021-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='activ',
            field=models.BooleanField(default=True),
        ),
    ]
