# Generated by Django 3.1.7 on 2021-02-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
