# Generated by Django 3.1.7 on 2021-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210228_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='activ',
            field=models.BooleanField(default=True),
        ),
    ]
