# Generated by Django 3.1.7 on 2021-02-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_progectcategory_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgectCategory',
            new_name='ProjectCategory',
        ),
    ]
