# Generated by Django 3.1.7 on 2021-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_project_projectcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
